### ISSUE TITLE
Adding `af_gnomade` flag to VEP annotation command

### ISSUE THREAD

**Issue by evelyn-schmidt** [wustl-oncology/analysis-wdls#174]
While @ksinghal28 was going through the process of [documenting how the pipeline files were collected/created](https://github.com/evelyn-schmidt/immuno_gcp_wdl_manuscript/blob/main/Preparing_references.md), we could not figure out how the `gnomad_fixed_b38_exome.vcf.gz` was created. The file is used in the VEP annotation step and seemed to be the V3 genome downloaded from the Gnomad Database but then some manual fixes were applied. These manual fixes and why they were needed are not clear. 

A way to make up for some ambiguity of how we made this file is to just include a VEP flag that was added to a newer version [`-af_gnomade`](https://useast.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_af_gnomad) which adds the gnomad annotations in the way we were previously doing and also adding more possibility useful flags.

We would like user to be able to turn this option on/off in the yaml file.

**Comment by malachig** [comment]
I think testing this involves a combination of the following two concepts:

1. Disable the custom argument we commonly pass into VEP that is defined in the immuno YAML file.  e.g. comment out the following lines in the YAML:

```
immuno.vep_custom_annotations:
- method: exact
 force_report_coordinates: true
  annotation:
    file: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/gnomad_fixed_b38_exome.vcf.gz"
    secondary_files:
    - "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/gnomad_fixed_b38_exome.vcf.gz.tbi"
    data_format: vcf
    name: gnomADe
    vcf_fields:
    - AF
    - AF_AFR
    - AF_AMR
    - AF_ASJ
    - AF_EAS
    - AF_FIN
    - AF_NFE
    - AF_OTH
    - AF_SAS
    gnomad_filter: true
    check_existing: true
```

2. Add a new parameter to vep.wdl

e.g.
```
~{if defined(af_gnomade) then "--af_gnomade" else ""} \ 
```

And of course define the WDL variable `af_gnomade` and pass it up to immuno.wdl so the user can set it or not.
